name: project_pkl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  mobile_scanner: ^7.2.0
  flutter_blue_plus: 1.31.18
  permission_handler: ^12.0.1
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# RATA KIRI MENTOK
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_2.jpg"
  min_sdk_size: 21

# RATA KIRI MENTOK
flutter_native_splash:
  color: "#F4F4F4"
  image: "assets/images/splash.png"
  android_12:
    image: "assets/images/splash.png"
